<?php declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */

$superPaymentConfig = $block->getData('superPaymentConfig');
$isDefaultMethod = $superPaymentConfig->getDefaultSelectedValue();
?>

<style>
    #payment-method-option-super_payment_gateway label:empty {
        height: 24px;
    }

    #payment-method-option-super_payment_gateway label:empty,
    #payment-method-option-super_payment_gateway label > *:not(.super-payment-method-title) {
        position: relative;
        color: transparent;
    }

    #payment-method-option-super_payment_gateway label:empty::before,
    #payment-method-option-super_payment_gateway label > *:not(.super-payment-method-title)::before {
        content: '';

        position: absolute;
        top: 7px;
        left: 0;
        width: 50px;
        height: 10px;
        background: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 52 12" xml:space="preserve"><circle fill="%23000" stroke="none" cx="6" cy="6" r="6"><animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.1s"/></circle><circle fill="%23000" stroke="none" cx="26" cy="6" r="6"><animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.2s"/></circle><circle fill="%23000" stroke="none" cx="46" cy="6" r="6"><animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.3s"/></circle></svg>') no-repeat center center / contain;
    }
</style>

<script>
    const initSuperPaymentMethodConfig = {
        isDefault: <?= json_encode($isDefaultMethod); ?>,
    };
</script>
<script src="<?= $block->getViewFileUrl('Superpayments_SuperPaymentHyva::js/checkout/super-payment-method.js') ?>"></script>
