<?php
/**@var Magento\Framework\View\Element\Template $block */
/**@var Superpayments\SuperPayment\ViewModel\MarketingBanner $viewModel */
$viewModel = $block->getData('view_model');
?>

<?php if ($viewModel->getPdpBanner()): ?>
    <?php
        $product = $block->getProduct();
        $price = $product->getFinalPrice();
        if (empty($price)) {
            $price = $product->getData('final_price') ?? $product->getData(\Magento\Catalog\Api\Data\ProductInterface::PRICE);
        }
        $price = $viewModel->getPriceConverter()->minorUnitAmount($price);

        $bannerData = $viewModel->getWebComponentData('product-detail');
    ?>

    <div class="super-container w-full mt-5 mb-8 [&>*]:my-0">
        <?= '<super-product-callout page="' . $bannerData['page'] . '" cartId="' . $bannerData['cart']['id'] . '" productAmount="' . $price . '" productQuantity="1"></super-product-callout>'; ?>
    </div>
<?php endif; ?>
