<?php
/**@var Magento\Framework\View\Element\Template $block */
/**@var Superpayments\SuperPayment\ViewModel\MarketingBanner $viewModel */
$viewModel = $block->getData('view_model');
?>

<?php if ($viewModel->getCartBanner()): ?>
    <?php $bannerData = $viewModel->getWebComponentData('cart', true); ?>

    <div class="super-container px-4 py-6 sm:px-6 flex justify-center mt-auto border-t border-container [&>*]:my-0 [&>*]:w-auto">
        <?= '<super-cart-callout cartAmount="' . $bannerData['minorUnitAmount'] . '" page="' .  $bannerData['page'] . '" cartId="' . $bannerData['cart']['id'] . '" cartItems="' . $viewModel->cartItemsEncode($bannerData['cart']['items']) . '"></super-cart-callout>'; ?>
    </div>
<?php endif; ?>
